# Generated by Django 5.1 on 2024-08-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='user_profile_images/'),
        ),
    ]
