# Generated by Django 5.1 on 2024-08-30 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_questions_options_alter_technology_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizhistory',
            options={'verbose_name_plural': 'Quiz History'},
        ),
        migrations.CreateModel(
            name='QuizHistoryQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='', max_length=500)),
                ('user_answer', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.questions')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizhistory')),
            ],
            options={
                'verbose_name_plural': 'Quiz History Questions',
            },
        ),
    ]
